export const vacancies = [
  {
    id: 1,
    profession: 'UI/UX дизайнер',
    url: 'ui-ux-designer',
    office: 'Уфа',
    date: '25.11.18',
    quickly: true,
    candidates: [
      {
        id: 1,
        name: 'Вася Пупкин',
        avatar: 'https://pp.userapi.com/c623900/v623900028/626c3/TJ9tAywL4lo.jpg',
        age: '27 лет',
        exp: '3 года',
        desiredSalary: '70 т.р.',
        status: 'Рассмотрение резюме',
        desiredProfession: 'UI/UX дизайнер',
        url: 'UI/UX designer',
      },
      {
        id: 2,
        name: 'Дмитрий Литвинов',
        avatar: 'https://pp.userapi.com/c623900/v623900028/626c3/TJ9tAywL4lo.jpg',
        age: '28 лет',
        exp: '5 лет',
        desiredSalary: '50 т.р.',
        status: 'Телефонное интервью',
        desiredProfession: 'UI/UX дизайнер',
        desiredProfessionEng: 'UI/UX designer',
      },
      {
        id: 3,
        name: 'Адиль Бомбилов',
        avatar: 'https://pp.userapi.com/c623900/v623900028/626c3/TJ9tAywL4lo.jpg',
        age: '25 лет',
        exp: '2 года',
        desiredSalary: '60 т.р.',
        status: 'Собеседование',
        desiredProfession: 'UI/UX дизайнер',
        desiredProfessionEng: 'UI/UX designer',
      },
      {
        id: 4,
        name: 'Семен Пирогов',
        avatar: 'https://pp.userapi.com/c844216/v844216688/10b24c/yDmxHInwoaw.jpg',
        age: '24 года',
        exp: '1 год',
        desiredSalary: '50 т.р.',
        status: 'Кандидат',
        desiredProfession: 'UI/UX дизайнер',
        desiredProfessionEng: 'UI/UX designer',
      },
      {
        id: 5,
        name: 'Руслан Маргунов',
        avatar: 'https://pp.userapi.com/c844216/v844216688/10b24c/yDmxHInwoaw.jpg',
        age: '22 года',
        exp: '3 года',
        desiredSalary: '80 т.р.',
        status: 'Рассмотрение резюме',
        desiredProfession: 'UI/UX дизайнер',
        desiredProfessionEng: 'UI/UX designer',
      },
    ],
  },
  {
    id: 2,
    profession: 'Front-end разработчик',
    url: 'front-end-developer',
    office: 'Москва',
    date: '06.02.19',
    candidates: []
  },
  {
    id: 3,
    profession: 'Проектировщик',
    url: 'designer',
    office: 'Екатеринбург',
    date: '02.03.19',
    candidates: []
  },
  {
    id: 4,
    profession: 'Back-end разработчик',
    url: 'back-end-developer',
    office: 'Москва',
    date: '05.11.18',
    quickly: true,
    candidates: []
  },
  {
    id: 5,
    profession: 'Менеджер проектов',
    url: 'project-manager',
    office: 'Ростов-на-Дону',
    date: '08.05.19',
    candidates: []
  },
  {
    id: 6,
    profession: 'PHP-разработчик',
    url: 'php-developer',
    office: 'Ростов-на-Дону',
    date: '05.12.18',
    quickly: true,
    candidates: []
  },
];
