const C = {
	// TABS constants
	ADD_TAB: 'ADD_TAB',
	UPDATE_TAB: 'UPDATE_TAB',
	REMOVE_TAB: 'REMOVE_TAB',

	// Salary Constants
	FETCH_SALARY_REQUEST: 'FETCH_SALARY_REQUEST',
	FETCH_SALARY_SUCCESS: 'FETCH_SALARY_SUCCESS',
	FETCH_SALARY_FAILURE: 'FETCH_SALARY_FAILURE',
	SORT_SALARY: 'SORT_SALARY',
	SET_MONTH: 'SET_MONTH',
}

export default C
