const C = {
	// TABS constants
	ADD_TAB: 'ADD_TAB',
	UPDATE_TAB: 'UPDATE_TAB',
	REMOVE_TAB: 'REMOVE_TAB',
	// 
	FETCH_CANDIDATES_REQUEST: 'FETCH_CANDIDATES_REQUEST',
	FETCH_CANDIDATES_SUCCESS: 'FETCH_CANDIDATES_SUCCESS',
	FETCH_CANDIDATES_FAILURE: 'FETCH_CANDIDATES_FAILURE',
	ARCHIVE_VACANCY_CANDIDATE: 'ARCHIVE_VACANCY_CANDIDATE',
	ARCHIVE_VACANCY_CANDIDATES: 'ARCHIVE_VACANCY_CANDIDATES',
}

export default C
