const C = {
  // workers constants
  FETCH_WORKERS_REQUEST: 'FETCH_WORKERS_REQUEST',
  FETCH_WORKERS_SUCCESS: 'FETCH_WORKERS_SUCCESS',
  FETCH_WORKERS_FAILURE: 'FETCH_WORKERS_FAILURE',
  FETCH_WORKER_REQUEST: 'FETCH_WORKER_REQUEST',
  FETCH_WORKER_SUCCESS: 'FETCH_WORKER_SUCCESS',
  FETCH_WORKER_FAILURE: 'FETCH_WORKER_FAILURE',
  OPEN_WORKER: 'OPEN_WORKER',
  CLOSE_WORKER: 'CLOSE_WORKER',
  FILTER_WORKERS: 'FILTER_WORKERS',

  // Vacancies constants
  FETCH_VACANCIES_REQUEST: 'FETCH_VACANCIES_REQUEST',
  FETCH_VACANCIES_SUCCESS: 'FETCH_VACANCIES_SUCCESS',
  FETCH_VACANCIES_FAILURE: 'FETCH_VACANCIES_FAILURE',
  FILTER_VACANCIES: 'FILTER_VACANCIES',
  FETCH_VACANCY_REQUEST: 'FETCH_VACANCY_REQUEST',
  FETCH_VACANCY_SUCCESS: 'FETCH_VACANCY_SUCCESS',
  FETCH_VACANCY_FAILURE: 'FETCH_VACANCY_FAILURE',
  REMOVE_VACANCY: 'REMOVE_VACANCY',
  ARCHIVE_VACANCY_CANDIDATE: 'ARCHIVE_VACANCY_CANDIDATE',
  ARCHIVE_VACANCY_CANDIDATES: 'ARCHIVE_VACANCY_CANDIDATES',

  // Candidates constants
  FETCH_CANDIDATES_REQUEST: 'FETCH_CANDIDATES_REQUEST',
  FETCH_CANDIDATES_SUCCESS: 'FETCH_CANDIDATES_SUCCESS',
  FETCH_CANDIDATES_FAILURE: 'FETCH_CANDIDATES_FAILURE',

  // TABS constants
  ADD_TAB: 'ADD_TAB',
  UPDATE_TAB: 'UPDATE_TAB',
  REMOVE_TAB: 'REMOVE_TAB',

  // Filter constants
  SET_FILTER_PROFESSION_VALUE: 'SET_FILTER_PROFESSION_VALUE',
  SET_FILTER_OFFICE_VALUE: 'SET_FILTER_OFFICE_VALUE',
  SET_FILTER_DEPARTMENT_VALUE: 'SET_FILTER_DEPARTMENT_VALUE',

  // Documents constants
  FETCH_DOCUMENTS_REQUEST: 'FETCH_DOCUMENTS_REQUEST',
  FETCH_DOCUMENTS_SUCCESS: 'FETCH_DOCUMENTS_SUCCESS',
  FETCH_DOCUMENTS_FAILURE: 'FETCH_DOCUMENTS_FAILURE',
  SORT_DOCUMENTS: 'SORT_DOCUMENTS',
  REMOVE_DOCUMENT: 'REMOVE_DOCUMENT',

  // Salary Constants
  FETCH_SALARY_REQUEST: 'FETCH_SALARY_REQUEST',
  FETCH_SALARY_SUCCESS: 'FETCH_SALARY_SUCCESS',
  FETCH_SALARY_FAILURE: 'FETCH_SALARY_FAILURE',
  SORT_SALARY: 'SORT_SALARY',
  SET_MONTH: 'SET_MONTH',

  // Offices constants
  FETCH_OFFICES_REQUEST: 'FETCH_OFFICES_REQUEST',
  FETCH_OFFICES_SUCCESS: 'FETCH_OFFICES_SUCCESS',
  FETCH_OFFICES_FAILURE: 'FETCH_OFFICES_FAILURE',
};

export default C;
